apiVersion: apps/v1
kind: Deployment
metadata:
  name: apirest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: apirest
        image: danielhdezsolis/apirest:1.0
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: apirest-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apirest-ingress
spec:
  rules:
  - host: api.jhernandezsolis.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apirest-service
            port:
              number: 3000



