version: "3"
services: 
  aplicacion:
    container_name: miapp
    restart: always
    build: .
    ports:
      - "3001:3000"
    links:
      - mongo
    volumes:
      - .:/app
  mongo:
    container_name: mymongo
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: