apiVersion: apps/v1
kind: Deployment
metadata:
  name: basemongo
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: basemongo
        image: danielhdezsolis/basemongo:1.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: db-storage
          mountPath: /data/db
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: db-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort
